// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/clipboarder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClipboarderService_SaveClipboard_FullMethodName = "/clipboarder.ClipboarderService/SaveClipboard"
	ClipboarderService_GetClipboard_FullMethodName  = "/clipboarder.ClipboarderService/GetClipboard"
)

// ClipboarderServiceClient is the client API for ClipboarderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipboarderServiceClient interface {
	SaveClipboard(ctx context.Context, in *SaveClipboardRequest, opts ...grpc.CallOption) (*SaveClipboardResponse, error)
	GetClipboard(ctx context.Context, in *GetClipboardRequest, opts ...grpc.CallOption) (*GetClipboardResponse, error)
}

type clipboarderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboarderServiceClient(cc grpc.ClientConnInterface) ClipboarderServiceClient {
	return &clipboarderServiceClient{cc}
}

func (c *clipboarderServiceClient) SaveClipboard(ctx context.Context, in *SaveClipboardRequest, opts ...grpc.CallOption) (*SaveClipboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveClipboardResponse)
	err := c.cc.Invoke(ctx, ClipboarderService_SaveClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboarderServiceClient) GetClipboard(ctx context.Context, in *GetClipboardRequest, opts ...grpc.CallOption) (*GetClipboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClipboardResponse)
	err := c.cc.Invoke(ctx, ClipboarderService_GetClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboarderServiceServer is the server API for ClipboarderService service.
// All implementations must embed UnimplementedClipboarderServiceServer
// for forward compatibility.
type ClipboarderServiceServer interface {
	SaveClipboard(context.Context, *SaveClipboardRequest) (*SaveClipboardResponse, error)
	GetClipboard(context.Context, *GetClipboardRequest) (*GetClipboardResponse, error)
	mustEmbedUnimplementedClipboarderServiceServer()
}

// UnimplementedClipboarderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClipboarderServiceServer struct{}

func (UnimplementedClipboarderServiceServer) SaveClipboard(context.Context, *SaveClipboardRequest) (*SaveClipboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveClipboard not implemented")
}
func (UnimplementedClipboarderServiceServer) GetClipboard(context.Context, *GetClipboardRequest) (*GetClipboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClipboard not implemented")
}
func (UnimplementedClipboarderServiceServer) mustEmbedUnimplementedClipboarderServiceServer() {}
func (UnimplementedClipboarderServiceServer) testEmbeddedByValue()                            {}

// UnsafeClipboarderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipboarderServiceServer will
// result in compilation errors.
type UnsafeClipboarderServiceServer interface {
	mustEmbedUnimplementedClipboarderServiceServer()
}

func RegisterClipboarderServiceServer(s grpc.ServiceRegistrar, srv ClipboarderServiceServer) {
	// If the following call pancis, it indicates UnimplementedClipboarderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClipboarderService_ServiceDesc, srv)
}

func _ClipboarderService_SaveClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveClipboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboarderServiceServer).SaveClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboarderService_SaveClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboarderServiceServer).SaveClipboard(ctx, req.(*SaveClipboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipboarderService_GetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboarderServiceServer).GetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboarderService_GetClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboarderServiceServer).GetClipboard(ctx, req.(*GetClipboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipboarderService_ServiceDesc is the grpc.ServiceDesc for ClipboarderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipboarderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clipboarder.ClipboarderService",
	HandlerType: (*ClipboarderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveClipboard",
			Handler:    _ClipboarderService_SaveClipboard_Handler,
		},
		{
			MethodName: "GetClipboard",
			Handler:    _ClipboarderService_GetClipboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/clipboarder.proto",
}
