// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/clipboarder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveClipboardRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClipboarderContent string                 `protobuf:"bytes,1,opt,name=clipboarder_content,json=clipboarderContent,proto3" json:"clipboarder_content,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SaveClipboardRequest) Reset() {
	*x = SaveClipboardRequest{}
	mi := &file_proto_clipboarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveClipboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveClipboardRequest) ProtoMessage() {}

func (x *SaveClipboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clipboarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveClipboardRequest.ProtoReflect.Descriptor instead.
func (*SaveClipboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_clipboarder_proto_rawDescGZIP(), []int{0}
}

func (x *SaveClipboardRequest) GetClipboarderContent() string {
	if x != nil {
		return x.ClipboarderContent
	}
	return ""
}

type SaveClipboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortKey      string                 `protobuf:"bytes,1,opt,name=short_key,json=shortKey,proto3" json:"short_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveClipboardResponse) Reset() {
	*x = SaveClipboardResponse{}
	mi := &file_proto_clipboarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveClipboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveClipboardResponse) ProtoMessage() {}

func (x *SaveClipboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clipboarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveClipboardResponse.ProtoReflect.Descriptor instead.
func (*SaveClipboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_clipboarder_proto_rawDescGZIP(), []int{1}
}

func (x *SaveClipboardResponse) GetShortKey() string {
	if x != nil {
		return x.ShortKey
	}
	return ""
}

type GetClipboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortKey      string                 `protobuf:"bytes,1,opt,name=short_key,json=shortKey,proto3" json:"short_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClipboardRequest) Reset() {
	*x = GetClipboardRequest{}
	mi := &file_proto_clipboarder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClipboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClipboardRequest) ProtoMessage() {}

func (x *GetClipboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clipboarder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClipboardRequest.ProtoReflect.Descriptor instead.
func (*GetClipboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_clipboarder_proto_rawDescGZIP(), []int{2}
}

func (x *GetClipboardRequest) GetShortKey() string {
	if x != nil {
		return x.ShortKey
	}
	return ""
}

type GetClipboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GetClipboard  string                 `protobuf:"bytes,1,opt,name=GetClipboard,proto3" json:"GetClipboard,omitempty"`
	IsFound       bool                   `protobuf:"varint,2,opt,name=is_found,json=isFound,proto3" json:"is_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClipboardResponse) Reset() {
	*x = GetClipboardResponse{}
	mi := &file_proto_clipboarder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClipboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClipboardResponse) ProtoMessage() {}

func (x *GetClipboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clipboarder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClipboardResponse.ProtoReflect.Descriptor instead.
func (*GetClipboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_clipboarder_proto_rawDescGZIP(), []int{3}
}

func (x *GetClipboardResponse) GetGetClipboard() string {
	if x != nil {
		return x.GetClipboard
	}
	return ""
}

func (x *GetClipboardResponse) GetIsFound() bool {
	if x != nil {
		return x.IsFound
	}
	return false
}

var File_proto_clipboarder_proto protoreflect.FileDescriptor

const file_proto_clipboarder_proto_rawDesc = "" +
	"\n" +
	"\x17proto/clipboarder.proto\x12\vclipboarder\"G\n" +
	"\x14SaveClipboardRequest\x12/\n" +
	"\x13clipboarder_content\x18\x01 \x01(\tR\x12clipboarderContent\"4\n" +
	"\x15SaveClipboardResponse\x12\x1b\n" +
	"\tshort_key\x18\x01 \x01(\tR\bshortKey\"2\n" +
	"\x13GetClipboardRequest\x12\x1b\n" +
	"\tshort_key\x18\x01 \x01(\tR\bshortKey\"U\n" +
	"\x14GetClipboardResponse\x12\"\n" +
	"\fGetClipboard\x18\x01 \x01(\tR\fGetClipboard\x12\x19\n" +
	"\bis_found\x18\x02 \x01(\bR\aisFound2\xc1\x01\n" +
	"\x12ClipboarderService\x12V\n" +
	"\rSaveClipboard\x12!.clipboarder.SaveClipboardRequest\x1a\".clipboarder.SaveClipboardResponse\x12S\n" +
	"\fGetClipboard\x12 .clipboarder.GetClipboardRequest\x1a!.clipboarder.GetClipboardResponseB1Z/github.com/username/shorturl/internal/rpc/protob\x06proto3"

var (
	file_proto_clipboarder_proto_rawDescOnce sync.Once
	file_proto_clipboarder_proto_rawDescData []byte
)

func file_proto_clipboarder_proto_rawDescGZIP() []byte {
	file_proto_clipboarder_proto_rawDescOnce.Do(func() {
		file_proto_clipboarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clipboarder_proto_rawDesc), len(file_proto_clipboarder_proto_rawDesc)))
	})
	return file_proto_clipboarder_proto_rawDescData
}

var file_proto_clipboarder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_clipboarder_proto_goTypes = []any{
	(*SaveClipboardRequest)(nil),  // 0: clipboarder.SaveClipboardRequest
	(*SaveClipboardResponse)(nil), // 1: clipboarder.SaveClipboardResponse
	(*GetClipboardRequest)(nil),   // 2: clipboarder.GetClipboardRequest
	(*GetClipboardResponse)(nil),  // 3: clipboarder.GetClipboardResponse
}
var file_proto_clipboarder_proto_depIdxs = []int32{
	0, // 0: clipboarder.ClipboarderService.SaveClipboard:input_type -> clipboarder.SaveClipboardRequest
	2, // 1: clipboarder.ClipboarderService.GetClipboard:input_type -> clipboarder.GetClipboardRequest
	1, // 2: clipboarder.ClipboarderService.SaveClipboard:output_type -> clipboarder.SaveClipboardResponse
	3, // 3: clipboarder.ClipboarderService.GetClipboard:output_type -> clipboarder.GetClipboardResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_clipboarder_proto_init() }
func file_proto_clipboarder_proto_init() {
	if File_proto_clipboarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clipboarder_proto_rawDesc), len(file_proto_clipboarder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clipboarder_proto_goTypes,
		DependencyIndexes: file_proto_clipboarder_proto_depIdxs,
		MessageInfos:      file_proto_clipboarder_proto_msgTypes,
	}.Build()
	File_proto_clipboarder_proto = out.File
	file_proto_clipboarder_proto_goTypes = nil
	file_proto_clipboarder_proto_depIdxs = nil
}
